// Code generated by go generate; DO NOT EDIT.
// Generated from doc comments in types.go and functions.go

package render

// methodDescriptions maps TypeName.MethodName to their documentation.
// This is auto-generated from doc comments on methods in types.go.
var methodDescriptions = map[string]string{
	"EventViewModel.AddDetail":                        "AddDetail adds a detail to the event's Details collection.",
	"EventViewModel.BasePortalURL":                    "BasePortalURL returns the portal base domain for the event.",
	"EventViewModel.IsAlarm":                          "IsAlarm returns true if event type is alarm.",
	"EventViewModel.IsCloudApp":                       "IsCloudApp reports whether the event application is Cloud.",
	"EventViewModel.IsCustomInsight":                  "IsCustomInsight returns true if event type is custom-insight.",
	"EventViewModel.IsInsight":                        "IsInsight returns true if event type is insight or custom-insight.",
	"EventViewModel.IsKmetricsApp":                    "IsKmetricsApp reports whether the event application is Kmetrics.",
	"EventViewModel.IsKtracApp":                       "IsKtracApp reports whether the event application is Ktrac.",
	"EventViewModel.IsMitigation":                     "IsMitigation returns true if event type is mitigation.",
	"EventViewModel.IsNMSApp":                         "IsNMSApp reports whether the event application is NMS.",
	"EventViewModel.IsProtectApp":                     "IsProtectApp reports whether the event application is DDoS.",
	"EventViewModel.IsSynthetic":                      "IsSynthetic returns true if event type is synthetic.",
	"EventViewModel.IsSyntheticsApp":                  "IsSyntheticsApp reports whether the event application is Synthetics.",
	"EventViewModel.IsTest":                           "IsTest reports whether the event is a test event.",
	"EventViewModel.IsTrafficApp":                     "IsTrafficApp reports whether the event application is Core.",
	"EventViewModel.TopLevelApplication":              "TopLevelApplication returns the last application segment.",
	"EventViewModel.UnmarshalJSON":                    "UnmarshalJSON decodes an EventViewModel with custom fields.",
	"EventViewModelDetail.GetValues":                  "GetValues returns the detail value(s) as a slice.",
	"EventViewModelDetail.IsList":                     "IsList reports whether the detail value is a list-like type.",
	"EventViewModelDetail.LabelOrName":                "LabelOrName returns Label if set, otherwise returns Name.",
	"EventViewModelDetail.UnmarshalJSON":              "UnmarshalJSON decodes an EventViewModelDetail with tags.",
	"EventViewModelDetails.General":                   "General returns details with an empty tag.",
	"EventViewModelDetails.Get":                       "Get retrieves a detail by name.",
	"EventViewModelDetails.GetStringValue":            "GetStringValue retrieves a string value by name.",
	"EventViewModelDetails.GetValue":                  "GetValue retrieves a value by name.",
	"EventViewModelDetails.Has":                       "Has checks if a detail with the given name exists.",
	"EventViewModelDetails.HasTag":                    "HasTag checks if any detail has the specified tag.",
	"EventViewModelDetails.Names":                     "Names returns all detail names.",
	"EventViewModelDetails.PrettifiedMetrics":         "PrettifiedMetrics returns metric details with formatted values.",
	"EventViewModelDetails.ToMap":                     "ToMap converts details to a name-to-value map.",
	"EventViewModelDetails.Values":                    "Values returns all detail values.",
	"EventViewModelDetails.ValuesWithTag":             "ValuesWithTag returns all detail values with the specified tag.",
	"EventViewModelDetails.WithNames":                 "WithNames filters details by the given names.",
	"EventViewModelDetails.WithTag":                   "WithTag filters details by the specified tag.",
	"NotificationViewModel.ActiveCount":               "ActiveCount returns the count of currently active events.",
	"NotificationViewModel.BasePortalURL":             "BasePortalURL returns the portal base URL (without path).",
	"NotificationViewModel.Copyrights":                "Copyrights returns the copyright string with current year.",
	"NotificationViewModel.Event":                     "Event returns the first event or nil if empty.",
	"NotificationViewModel.Events":                    "Events returns all events as a slice.",
	"NotificationViewModel.Headline":                  "Headline returns the generated headline text.",
	"NotificationViewModel.InactiveCount":             "InactiveCount returns the count of inactive events.",
	"NotificationViewModel.IsAtLeastOneEvent":         "IsAtLeastOneEvent returns true if at least one event exists.",
	"NotificationViewModel.IsInsightsOnly":            "IsInsightsOnly returns true if all events are from Insights.",
	"NotificationViewModel.IsMultipleEvents":          "IsMultipleEvents returns true if notification message is triggered with more than one event (currently only insight digest notifications).",
	"NotificationViewModel.IsSingleCustomInsightOnly": "IsSingleCustomInsightOnly returns true if single custom insight event.",
	"NotificationViewModel.IsSingleEvent":             "IsSingleEvent returns true if notification message is triggered with a single event.",
	"NotificationViewModel.IsSynthOnly":               "IsSynthOnly is an alias for IsSyntheticsOnly.",
	"NotificationViewModel.IsSyntheticsOnly":          "IsSyntheticsOnly returns true if all events are from Synthetics.",
	"NotificationViewModel.NotificationsSettingsURL":  "NotificationsSettingsURL returns the notification channels URL.",
	"NotificationViewModel.NowDate":                   "NowDate returns the current date formatted as 'January 2, 2006'.",
	"NotificationViewModel.NowDatetime":               "NowDatetime returns the current time as '2006-01-02 15:04:05 UTC'.",
	"NotificationViewModel.NowRFC3339":                "NowRFC3339 returns the current time in RFC3339 format, example: 2006-01-02T15:04:05Z",
	"NotificationViewModel.NowUnix":                   "NowUnix returns the current time as Unix timestamp.",
	"NotificationViewModel.Summary":                   "Summary returns the generated summary text.",
	"NotificationViewModel.SyntheticsDashboardURL":    "SyntheticsDashboardURL returns the synthetics dashboard URL.",
	"NotificationViewModel.UnmarshalJSON":             "UnmarshalJSON decodes a NotificationViewModel with derived fields.",
}

// functionMetadata contains metadata for all template functions.
// This is auto-generated from doc comments in functions.go.
var functionMetadata = []*SchemaFunction{
	{
		Name:        "compactJSON",
		Signature:   "(s string) string",
		Description: "compactJSON compacts a JSON string by removing whitespace.",
		Category:    "conversion",
	},
	{
		Name:        "explodeJSONKeys",
		Signature:   "(s string) string",
		Description: "explodeJSONKeys extracts object key-values without braces.",
		Category:    "conversion",
	},
	{
		Name:        "importanceLabel",
		Signature:   "(severity types.ViewModelImportance) string",
		Description: "importanceLabel returns the title-case label for an importance level.",
		Category:    "formatting",
	},
	{
		Name:        "importanceToColor",
		Signature:   "(severity types.ViewModelImportance) string",
		Description: "importanceToColor returns the hex color code for an importance level.",
		Category:    "formatting",
	},
	{
		Name:        "importanceToEmoji",
		Signature:   "(severity types.ViewModelImportance) string",
		Description: "importanceToEmoji returns the emoji(s) for an importance level.",
		Category:    "formatting",
	},
	{
		Name:        "join",
		Signature:   "(index int) string",
		Description: "join returns a comma for index > 0, empty string for index 0.",
		Category:    "utility",
	},
	{
		Name:        "joinWith",
		Signature:   "(index int, join string) string",
		Description: "joinWith returns the separator for index > 0, empty string for index 0.",
		Category:    "utility",
	},
	{
		Name:        "split",
		Signature:   "(s string, sep string) []string",
		Description: "split splits a string by the given separator.",
		Category:    "string",
	},
	{
		Name:        "timeRfc3339",
		Signature:   "(input interface{}) string",
		Description: "timeRfc3339 converts various time formats to RFC3339.",
		Category:    "time",
	},
	{
		Name:        "title",
		Signature:   "(s string) string",
		Description: "title converts a string to title case.",
		Category:    "string",
	},
	{
		Name:        "toJSON",
		Signature:   "(v interface{}) string",
		Description: "toJSON converts any value to a JSON string.",
		Category:    "conversion",
	},
	{
		Name:        "toLower",
		Signature:   "(s string) string",
		Description: "toLower converts a string to lowercase.",
		Category:    "string",
	},
	{
		Name:        "toUpper",
		Signature:   "(s string) string",
		Description: "toUpper converts a string to uppercase.",
		Category:    "string",
	},
	{
		Name:        "trimSpace",
		Signature:   "(s string) string",
		Description: "trimSpace removes leading and trailing whitespace.",
		Category:    "string",
	},
}

// enumDefinitions contains all enum types.
// This is auto-generated from type definitions and const blocks in types.go.
var enumDefinitions = map[string]*SchemaEnum{
	"DetailTag": {
		Values:      []string{"", "general", "metric", "dimension", "url", "device", "device_labels", "device_label"},
		Description: "DetailTag categorizes event details.",
	},
	"EventType": {
		Values:      []string{"alarm", "insight", "custom-insight", "synthetic", "mitigation", "generic"},
		Description: "EventType represents the notification event category.",
	},
	"ViewModelImportance": {
		Values:      []string{"None", "Healthy", "Notice", "Minor", "Warning", "Major", "Severe", "Critical"},
		Description: "ViewModelImportance represents severity levels for view model events.",
	},
}

// getMethodDescription looks up a method's documentation by type and method name.
// Returns empty string if not found.
func getMethodDescription(typeName, methodName string) string {
	key := typeName + "." + methodName
	if desc, ok := methodDescriptions[key]; ok {
		return desc
	}
	return ""
}

// extractFunctions returns all template function metadata.
// The slice is sorted by function name for consistency.
func extractFunctions() []*SchemaFunction {
	return functionMetadata
}

// extractEnums returns all enum definitions.
// Enums are auto-generated from type definitions and const blocks.
func extractEnums() map[string]*SchemaEnum {
	return enumDefinitions
}
